modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="errmod"
version="1.0.0"
displayName="Error"
displayURL="https://mcreator.net"
credits="With help of https://mcreator.net"
authors="kuko"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.errmod]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.176,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.errmod]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration